server:
  port: 8081

spring:
  application:
    name: service-client
  cloud:
    consul:
      enabled: false # Disable Consul
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000